<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@yield('title') - {{ config('app.name') }}</title>
    <base href="{{asset('')}}" />
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('') }}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <meta name="csrf_token" content="{{ csrf_token() }}">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" href="{{ asset('css/tailwind.output.css') }}" />
    <link rel="stylesheet" href="{{ asset('css/app.css') }}?time={{ time() }}" />
    <link rel="stylesheet" href="{{ asset('css/tooltip.css') }}">

    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
        integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
        integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" defer></script>
</head>

<body>
    <noscript>Vui lòng bật Javascript của trình duyệt</noscript>
    <div id="app" class="flex h-screen bg-gray-50 dark:bg-gray-900" user="{{ auth()->user()->id ?? 0 }}"
        :class="{ 'overflow-hidden': isSideMenuOpen }">

        <!-- Loading -->
        <transition enter-class="opacity-100" enter-to-class="opaccity-100" leave-class="transition ease-in"
            leave-to-class="opacity-0">
            <div v-if="this.isLoad"
                class="fixed z-[100] duration-150 h-full w-full bg-[#ffffff] flex items-center dark:bg-gray-800 justify-center flex-col">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" xmlns:xlink="http://www.w3.org/1999/xlink"
                    style="display: block; shape-rendering: auto;" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
                    <circle cx="50" cy="50" fill="none" stroke="#4f46e5" stroke-width="10" r="35"
                        stroke-dasharray="164.93361431346415 56.97787143782138">
                        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s"
                            values="0 50 50;360 50 50" keyTimes="0;1" />
                    </circle>
                    <!-- [ldio] generated by https://loading.io/ -->
                </svg>
                <span class="text-sm my-2 dark:text-gray-200">
                    {{ __('Đang tải...') }}
                </span>
            </div>
        </transition>

        <!-- Desktop sidebar -->
        @include('layouts.navigate')
        <div class="flex flex-col flex-1 w-full">
            <header class="z-10 py-2 bg-[#ffffff] shadow-md dark:bg-gray-800">
                @include('layouts.header')
            </header>
            <main class="h-full overflow-y-auto">
                @yield('main')
            </main>
        </div>
        <transition enter-class="opacity-0" enter-to-class="opacity-100" leave-to-class="opacity-0">
            <profile v-if="isModalProfile" class="z-50 transition ease-in-out duration-150"
                :user="{{ auth()->user()->load(['role']) }}" @toggle-profile="toggleProfileModal"></profile>
        </transition>
        <transition enter-class="opacity-0" enter-to-class="opacity-100" leave-to-class="opacity-0">
            <div class="w-full h-full fixed top-0 left-0 flex items-center backdrop-blur-lg z-50"
                v-if="this.isOpenSettingModal">
                <div class="
                profile__modal
                lg:w-2/5
                w-full
                h-fit
                flex flex-col
                bg-[#ffffff]
                mx-auto
                rounded-lg
                p-4
                z-50
                shadow
                dark:bg-gray-800 dark:text-gray-200" v-on-clickaway="toggleSettingModal">
                    <div class="
                    flex
                    items-center
                    justify-between
                    border-bottom border-gray-200
                    py-2
                    ">
                        <h2 class="text-2xl font-bold">Cài đặt</h2>
                        <button class="rounded-lg border border-opacity-75" @click="toggleSettingModal">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                                stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                    </div>
                    <form action="{{ route('auth.password.request.change') }}" method="POST">
                        <div class="flex justify-between my-3">
                            @csrf
                            <div class="text-base grow pl-2 flex flex-col">
                                <label class="my-1">
                                    <span>Mật khẩu hiện tại</span>
                                    <input class="
                                block
                                w-full
                                mt-1
                                text-sm
                                dark:border-gray-600 dark:bg-gray-700
                                focus:border-purple-400
                                focus:outline-none
                                focus:shadow-outline-purple
                                dark:text-gray-300 dark:focus:shadow-outline-gray
                                form-input
                            " type="password" name="current_password" />
                                </label>
                                <label class="my-1">
                                    <span>Mật khẩu mới</span>
                                    <input class="
                                block
                                w-full
                                mt-1
                                text-sm
                                dark:border-gray-600 dark:bg-gray-700
                                focus:border-purple-400
                                focus:outline-none
                                focus:shadow-outline-purple
                                dark:text-gray-300 dark:focus:shadow-outline-gray
                                form-input
                            " type="password" name="new_password" />
                                </label>
                                <label class="my-1">
                                    <span>Xác nhận mật khẩu</span>
                                    <input class="
                                block
                                w-full
                                mt-1
                                text-sm
                                dark:border-gray-600 dark:bg-gray-700
                                focus:border-purple-400
                                focus:outline-none
                                focus:shadow-outline-purple
                                dark:text-gray-300 dark:focus:shadow-outline-gray
                                disabled:bg-gray-200
                                dark:disabled:bg-gray-700
                                form-input
                            " type="password" name="confirm_password" />
                                </label>
                                <div class="flex items-center justify-end text-sm mt-3">
                                    <button class="
                                    px-4
                                    py-2
                                    border border-gray-200
                                    text-[#000000]
                                    dark:text-gray-200
                                    mx-2
                                    rounded
                                " @click="toggleSettingModal">
                                        Đóng
                                    </button>
                                    <button type="submit" class="px-4 py-2 bg-purple-600 text-white rounded">
                                        Cập nhật
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </transition>
        [[ setSelectedMenu({{ $current }}) ]]
    </div>
    <script src="{{ asset('js/app.js') }}?time={{ time() }}" defer></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    @yield('script')

</body>

</html>